src/SFA.DAS.CloudService/Configuration/ServiceDefinition.Release.csdef, src/SFA.DAS.CloudService/ServiceConfiguration.Cloud.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.Local.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.Release.cscfg, src/SFA.DAS.CloudService/ServiceDefinition.csdef, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Web.Release.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/Web.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
- Removed EventHub NLog target
=> Added redis NLog target

src/SFA.DAS.ProviderApprenticeshipsService.Web/App_Start/RouteConfig.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipViewModelValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Create.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Shared/ValidationSummary.cshtml
- Updated add apprentice view from Employer
- Updated routes
- Updated edit apprentice with new field
- Changed some forms to links.
=> Added field ULN

src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/AcknowledgementViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/FinishEditingViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/SubmitCommitmentModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/SubmitCommitmentViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Acknowledgement.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/FinishEditing.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Submit.cshtml
You can Finish Editing and select "send for amendments". This will call the SubmitCommitmentCommand which currently changes patches commitment with "Active" status. So obviously will need changing based on the new statuses and workflow.
=> Finish editing

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Acknowledgement.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Create.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/FinishEditing.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Submit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Home/Index.cshtml
Sarah needed some copy changes which are now in place.
=> Content changes 

src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj
to improve how errors are logged
=> enabled pdb for release build on web/api project

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Acknowledgement.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Create.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/FinishEditing.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Submit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Shared/_Layout.cshtml
- Added page ID in body element
- Added no-js script for GTM
=> Google analytics

src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SubmitCommitment/SubmitCommitmentCommand.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SubmitCommitment/SubmitCommitmentCommandHandler.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/Orchestrators/WhenApproveCommitment.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/SFA.DAS.ProviderApprenticeshipsService.Web.Tests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/FinishEditingViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/SubmitCommitmentViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/Types/SaveOrSendStatus.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/FinishEditing.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Submit.cshtml
Will do employer after this PR is completed. 
/c
=> Replace saveorsend strings

src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/AccountController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Global.asax.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/AccountHomeViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/AccountOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/NoAccount.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/NoAgreement.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
=> handle invalid provider statuses

src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SubmitCommitment/SubmitCommitmentCommand.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SubmitCommitment/SubmitCommitmentCommandHandler.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/Queries/GetApprenticeship/GetApprenticeshipQueryHandler.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/Queries/GetApprenticeship/GetApprenticeshipQueryRequest.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/Orchestrators/WhenApproveCommitment.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/SFA.DAS.ProviderApprenticeshipsService.Web.Tests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/WhenGettingStatusOfCommitment.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/RequestStatus.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/AccountOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentStatusCalculator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/ICommitmentStatusCalculator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
Includes:
- Status messages:
- not working until commitment API is done)
- Got tests for all scenarios
- Update to latest commitment types and client
- Sending LastAction instead of AgreementType
- Removed commitment id when getting an apprentiship
=> Ping pong status

src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/SFA.DAS.ProviderApprenticeshipsService.Web.Tests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/StatusCalculator/WhenEditStatusIsWithBoth.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/StatusCalculator/WhenEditStatusIsWithEmployer.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/StatusCalculator/WhenEditStatusIsWithProvider.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.Tests/WhenGettingStatusOfCommitment.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentStatusCalculator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/ICommitmentStatusCalculator.cs
Started splitting status tests in to multiple files.
=> Update Calculator with missed scenario

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/WhenValidatingApprenticeshipViewModelForApproval.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Extensions/HtmlHelperExtensions.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/ApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/ExtendedApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipViewModelApproveValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml
@rajeshdigital Can you review add the front end if you have time? 
/c
=> Added validation for approval

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/WhenValidatingApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/WhenValidatingApprenticeshipViewModelForApproval.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipViewModelValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Create.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie6.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie7.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie8.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/javascripts/apprentice/dropdown.js, src/SFA.DAS.ProviderApprenticeshipsService.Web/src/sass/_custom.scss
Updated the validation that is applied. There was some unexpected rules that have been removed.
=> Datetime update

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Models/DateTimeViewModelTests.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/WhenValidatingApprenticeshipViewModelForApproval.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/ApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/Types/DateTimeViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipViewModelValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Create.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml
* DCM-149
* Need to do for employer a well?
=> DCM-149 - Date with 2 digit

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/WhenValidatingApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/ApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipViewModelValidator.cs
Regex now allows thousand comma separators
=> Update Cost Regex

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Acknowledgement.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Create.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/FinishEditing.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Submit.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Home/Privacy.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Home/Terms.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie6.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie7.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie8.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/src/sass/_custom.scss
Accessibility fix for Breadcrumbs.  DCM-152 now complete.
=> Provider ui sprint 3

src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/AcknowledgementViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Acknowledgement.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/RequestApproved.cshtml
- Back to Your cohort if no cohort in list
=> DCM-259 -> Changing link on receipt pages [Provider]

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenDeletingApprenticeship.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingDeleteApprenticeshipConfirmation.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/CommitmentDetailsViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml
Fixed text if cohorts > 1 on list page
=> Fixing back link on cohort details page

src/SFA.DAS.PAS.ContractAgreements.WebJob/App.Debug.config, src/SFA.DAS.PAS.ContractAgreements.WebJob/App.Release.config, src/SFA.DAS.PAS.ContractAgreements.WebJob/SFA.DAS.PAS.ContractAgreements.WebJob.csproj
Not sure how the build/release is working but I have tried to copy the web.
=> Added config transform for WebJob

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/WhenValidatingRecordsBulkUpload.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenUploadingFile.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/WhenValidatingApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/WhenValidatingApprenticeshipViewModelForApproval.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/BulkUpload/CsvRecord.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/BulkUpload/BulkUploadFileParser.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipBaseValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipViewModelApproveValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Create.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Edit.cshtml
Please review and merge 3 x DCM-266 branches in EAS, Provider, and Commitments repositories together as they are inter-dependent
=> Dcm 266 remove nino

src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/Commands/SendNotification/WhenValidatingCommand.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SendNotification/SendNotificationCommand.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SendNotification/SendNotificationCommandHandler.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SendNotification/SendNotificationCommandValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SubmitCommitment/SubmitCommitmentCommandHandler.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Configuration/EmailTemplateConfigurationItem.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Configuration/EmailTemplateType.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Configuration/ProviderApprenticeshipsServiceConfiguration.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/DependencyResolution/DefaultRegistry.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
Can be reviewed but needs to be merged with the CommitmentsApi and Employer pull requests.
Note: Still waiting for the Email Content so will have to update the tokens being passed to the Notification Api.
The following changes have also been made:
- Provider configuration updated (NotificationsApi & Email Templates)
- Notifications Templates Configuration (New Template Definition added)
=> Send Email to Employer when submitting commitment

src/SFA.DAS.ProviderApprenticeshipsService.Application/Commands/SubmitCommitment/SubmitCommitmentCommandHandler.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenApproveCommitment.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGetCohorts.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/StatusCalculator/WhenEditStatusIsWithBoth.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/StatusCalculator/WhenEditStatusIsWithEmployer.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/StatusCalculator/WhenEditStatusIsWithProvider.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/CommitmentController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentStatusCalculator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/ICommitmentStatusCalculator.cs
TBC and merged along with commitments Commitments PR:
https://github.com/SkillsFundingAgency/das-commitments/compare/DCM-269_Provider_New_Cohorts?expand=1
=> Dcm 269 provider new cohorts

src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/BulkUpload/UploadError.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/Types/DateTimeViewModel.cs
Can be stored in Redis Session store
=> Made classes Serializable

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Shared/_Layout.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie6.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie7.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie8.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/src/sass/_custom.scss
=> Dcm 561 floating headers

src/SFA.DAS.API/ServiceConfiguration.PreProd.cscfg, src/SFA.DAS.API/ServiceConfiguration.Release.cscfg, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/NotificationSettings.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/NotificationUnsubscribe.cshtml
This branch is released. Please review and merge
=> Provider notifications release

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Shared/_Layout.cshtml
This branch has been released. Please review and merge
=> Beta banner removal

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/BulkUploadTestHelper.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/ApprenticeshipValidationTestBase.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenValidatingApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/ApprenticeshipBulkUpload/ApprenticeshipBulkUploadValidationTestBase.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/WhenValidatingCsvRecord.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/ApprenticeshipListItemGroupViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/ApprenticeshipListItemViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/FinishEditingViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/BulkUpload/BulkUploadValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/BulkUpload/InstrumentedBulkUploadValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprenticeshipUploadModelValidator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/FinishEditing.cshtml
Remove Academic Year From Left Of Line code changes
=> DCM-885_Remove pre-approval changes from academic year release

src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/ManageApprenticesController.cs
Just needs one reviewer please @carlbm or @davehowlett
=> Fixes issue where transaction type was wrong in CoC

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/WhenGettingUploadModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingCommitmentViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/CommitmentDetailsViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/BulkUploadOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Commitment/Details.cshtml
=> Dpp 1099 remove bulk upload for transfers

src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/WhenGettingUploadModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/Mappers/WhenMappingApprenticeship.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingApprenticeship.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingApprovedViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingCommitmentViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingCreateApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/BulkUploadOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/Mappers/ApprenticeshipMapper.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
=> DPP-1191 Updated ProviderApprenticeship service to use new Commitment API nuget

src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/WhenGettingUploadModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/Mappers/WhenMappingApprenticeship.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingApprenticeship.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingApprovedViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingCommitmentViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingCreateApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/BulkUploadOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/Mappers/ApprenticeshipMapper.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
… API nuget (#350)
* updated ProviderApprenticeship service to use new CommitmentAPI with TransferSenderclass
* Fixed tests and the upload assertion
* fix test
=> TransfersBaseBranch into Master including all MVS Stories

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenValidatingApprenticeshipViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Validation/ApprovedApprenticeship/WhenCallingValidateApprovedEndDate.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Validation/ApprovedApprenticeshipValidator.cs
https://skillsfundingagency.atlassian.net/browse/DPP-1556
=> DPP-1556 Add/Edit Apprenticeship Generic Error On Save If EndDate Not Entered

src/SFA.DAS.PAS.Account.Api.Client/SFA.DAS.PAS.Account.Api.Client.csproj, src/SFA.DAS.PAS.Account.Api.Client/packages.config, src/SFA.DAS.PAS.Account.Api.UnitTests/app.config, src/SFA.DAS.PAS.Account.Api/Web.config, src/SFA.DAS.PAS.ContractAgreements.WebJob.UnitTests/app.config, src/SFA.DAS.PAS.ContractAgreements.WebJob/App.config, src/SFA.DAS.PAS.ContractAgreements.WebJob/SFA.DAS.PAS.ContractAgreements.WebJob.csproj, src/SFA.DAS.PAS.ContractAgreements.WebJob/packages.config, src/SFA.DAS.PAS.Infrastructure.UnitTests/app.config, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/app.config, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/app.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/app.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/app.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Web.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
https://skillsfundingagency.atlassian.net/browse/DPP-1390
=> DPP-1390 Modify Commitments To Write Stop And Pause Dates For All Events

src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
https://skillsfundingagency.atlassian.net/browse/DPP-1575
=> DPP-1575 Commitments Api Client .Net Core Support

src/SFA.DAS.PAS.Account.Api/Controllers/AccountController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/Mappers/WhenMappingApprenticeshipDetails.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/ApprenticeshipDetailsViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/Mappers/ApprenticeshipMapper.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/ManageApprentices/Details.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
https://skillsfundingagency.atlassian.net/browse/DPP-1513
=> DPP-1513 Display AgreementId On Commitment Details Ui

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Account/WhenGettingProvider.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/AccountHomeViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/AccountOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie6.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie7.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie8.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/src/sass/_custom.scss
strongly influenced by previous branch for 16/17 cut-off.
=> DPP-1641 banner end of year

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/WhenGettingUploadModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/UploadApprenticeshipsViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/BulkUploadOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/BulkUpload/UploadApprenticeships.cshtml
Note, this is to merge the guidance text work into the existing transfers bulk upload story.
=> DPP-1657 guidance text

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/ManageApprentices/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie6.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie7.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie8.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/src/sass/_custom.scss
Ive changed base to be DPP-1249 as that has been merged into this branch.
=> DPP-1155 display total count

src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/DependencyResolution/DefaultRegistry.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Web.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
https://skillsfundingagency.atlassian.net/browse/AML-3150
=> AML-3150 Update provider relationships api client

src/SFA.DAS.ProviderUrlHelper/SFA.DAS.ProviderUrlHelper.csproj
=> CV-34-FixCoreAppCompatibility

src/SFA.DAS.CloudService/Configuration/ServiceDefinition.Cloud.csdef, src/SFA.DAS.CloudService/Configuration/ServiceDefinition.Release.csdef, src/SFA.DAS.CloudService/ServiceConfiguration.Cloud.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.Local.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.MO.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.PreProd.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.Release.cscfg, src/SFA.DAS.CloudService/ServiceDefinition.csdef, src/SFA.DAS.ProviderApprenticeshipsService.Domain/Models/FeatureToggles/Recruit.cs, src/SFA.DAS.ProviderApprenticeshipsService.Domain/SFA.DAS.ProviderApprenticeshipsService.Domain.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Account/WhenGettingAccountHomeViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/AccountHomeViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/AccountOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Shared/_Layout.cshtml, src/SFA.DAS.ProviderUrlHelper/Core/ProviderUrlHelperExtensions.cs, src/SFA.DAS.ProviderUrlHelper/Framework/ProviderUrlHelperExtensions.cs, src/SFA.DAS.ProviderUrlHelper/ILinkGenerator.cs, src/SFA.DAS.ProviderUrlHelper/LinkGenerator.cs, src/SFA.DAS.ProviderUrlHelper/ProviderUrlConfiguration.cs, src/SFA.DAS.ProviderUrlHelperTests/LinkGeneratorTests.cs
See also config changes: https://github.com/SkillsFundingAgency/das-employer-config/pull/237
=> Cv 21 add recruit link

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Home/Privacy.cshtml
I've not run the application so if someone could double check the viewing of `/privacy` to make sure the table is OK. Thanks
=> ER-1110 - Updated privacy page with extra cookie information

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Home/Index.cshtml
=> ER-995_Update Index.cshtml

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Authorization/AuthorizationContextProviderTests.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Helpers/HtmlExtensionsTests/WhenCallingCanShowReservationsLink.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Authorization/AuthorizationContextProvider.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Helpers/HtmlExtensions.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/Index.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Shared/_Layout.cshtml
There is no permission toggle around the new links as agreed with team but these are subject to a feature toggle.
=> CV-157 Add links to manage reservations

src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Shared/_Layout.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie6.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie7.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen-ie8.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/dist/css/screen.css, src/SFA.DAS.ProviderApprenticeshipsService.Web/src/sass/_header.scss
- Changed site title to 'Apprenticeships' and removed crown gov logo
=> Cv 269 navbar update

src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Application/SFA.DAS.ProviderApprenticeshipsService.Application.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Application/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/WhenCreatingRecordsBulkUpload.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/BulkUpload/WhenValidatingBulkUploadFileAttributes.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/ApprenticeshipValidationTestBase.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingDraftCohorts.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenGettingHashedIdsFromCommitmentDetails.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Commitments/WhenUploadingFile.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Orchestrators/Formatters/GivenACsvFormatter.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/DependencyResolution/DefaultRegistry.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/DependencyResolution/IoC.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Orchestrators/CommitmentOrchestrator.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/Web.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
Introduces encoding service
Corrects TransferSenderId encoding
Returns AccountLegalEntityPublicHashedId from api viewmodel instead of encoding
=> Reservations Add Another Defect fix

src/SFA.DAS.API/Configuration/ServiceDefinition.Cloud.csdef, src/SFA.DAS.API/Configuration/ServiceDefinition.Release.csdef, src/SFA.DAS.API/ServiceConfiguration.Cloud.cscfg, src/SFA.DAS.API/ServiceConfiguration.Local.cscfg, src/SFA.DAS.API/ServiceConfiguration.MO.cscfg, src/SFA.DAS.API/ServiceConfiguration.PreProd.cscfg, src/SFA.DAS.API/ServiceConfiguration.Release.cscfg, src/SFA.DAS.API/ServiceDefinition.csdef, src/SFA.DAS.CloudService/Configuration/ServiceDefinition.Cloud.csdef, src/SFA.DAS.CloudService/Configuration/ServiceDefinition.Release.csdef, src/SFA.DAS.CloudService/ServiceConfiguration.Cloud.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.Local.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.MO.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.PreProd.cscfg, src/SFA.DAS.CloudService/ServiceConfiguration.Release.cscfg, src/SFA.DAS.CloudService/ServiceDefinition.csdef
Removed Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString from cloud services' configuration files as it is unused.
=> Removed Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Attributes/DasRoleCheck/When_DasRoleCheckActionFilter_OnActionExecuting.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Attributes/DasRoleCheckActionFilter.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Extensions/HttpContextBaseExtensions.cs
=> CON-2516 Check for the presence of a valid service claim within a list of service claims

src/SFA.DAS.PAS.ContractAgreements.WebJob/SFA.DAS.PAS.ContractAgreements.WebJob.csproj, src/SFA.DAS.PAS.ContractAgreements.WebJob/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Data/BaseRepository.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Data/ProviderAgreementStatusRepository.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Data/ProviderRepository.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Data/UserRepository.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/Data/UserSettingsRepository.cs, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/SFA.DAS.ProviderApprenticeshipsService.Infrastructure.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Infrastructure/packages.config, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj, src/SFA.DAS.ProviderApprenticeshipsService.Web/packages.config
moved BaseRepository from SFA.DAS.Sql.Client
=> Con 4278 sql mi

azure-pipelines.yml, pipeline-templates/job/code-build.yml, pipeline-templates/job/dacpac-build.yml, pipeline-templates/job/deploy.yml
A standalone branch just for the pipeline changes, but as part of a wider .NET Upgrade branch
=> restructure build and deploy steps

src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/AccountController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/SFA.DAS.ProviderApprenticeshipsService.Web.csproj
Commit Details:
1) Update DfESignIn Nuget Package to latest
2) Intercept OpenIdConnect Signout Event with OnSignedOutCallbackRedirect option to destroy the OpenIdConnect Cookie and SignOut the User Auth session
Story: https://skillsfundingagency.atlassian.net/browse/FAI-886
=> FAI-886 Return logged off users to the service start screen

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Controllers/HomeControllerTest.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/HomeController.cs
Commit Details:
Redirect the User to Account Home Page if they are authenticated. Unit testing to cover the logic.
Story: https://skillsfundingagency.atlassian.net/browse/FAI-812
=> FAI-812 Redirect the User to Account Home Page if they are authenticated.

azure/template.json, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Controllers/ErrorControllerTest.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/ErrorController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/Error/Error403ViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Error/_Error403.cshtml, src/SFA.DAS.ProviderApprenticeshipsService.Web/appsettings.json
Commit Details:
403 Forbidden Error Page with content relevant to DfESignIn
https://skillsfundingagency.atlassian.net/browse/FAI-906#
=> FAI-906 Amend access denied page

src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Controllers/AccountControllerTest.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web.UnitTests/Models/Account/WhenBuildingChangeOfDetailsViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Controllers/AccountController.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Models/Account/ChangeOfDetailsViewModel.cs, src/SFA.DAS.ProviderApprenticeshipsService.Web/Views/Account/ChangeSignInDetails.cshtml
Commit Details:
1. Added Back link to the Change of Details Page
2. DfESignIn Profile Page link generation based on ResourceEnvironment 
3. Unit testing added to cover the above changes
Story: https://skillsfundingagency.atlassian.net/browse/FAI-986
=> FAI-986 COD Back Btn & Profile Page Link
